//! Docker MCP Gateway isolation profile generation.
//!
//! Kotro does **not** ship a container runtime. Instead, `kotro-proxy isolate
//! docker` emits a restrictive Docker Compose / MCP Gateway profile that the
//! user can apply to an MCP server: read-only mounts, explicit egress hosts,
//! CPU/memory limits, and secret injection via env files that never land in
//! the image.
//!
//! The generated artifacts are written to `<out-dir>/` and never executed by
//! Kotro itself.

use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
pub struct IsolateOptions {
    /// Logical MCP server name (used in labels / service name).
    pub name: String,
    /// Image to run, e.g. `ghcr.io/example/mcp-files:1.2.3`.
    pub image: String,
    /// Absolute host paths mounted read-only into `/workspace`.
    pub read_only_mounts: Vec<PathBuf>,
    /// Absolute host paths mounted read-write (default: none — prefer RO).
    pub read_write_mounts: Vec<PathBuf>,
    /// Hostnames the container may reach. Empty = no egress.
    pub egress_hosts: Vec<String>,
    /// CPU limit as a Docker Compose float string (e.g. `"0.5"`).
    pub cpus: String,
    /// Memory limit (e.g. `"256m"`).
    pub memory: String,
    /// Path to a secrets env-file mounted at runtime (never baked into image).
    pub secrets_env_file: Option<PathBuf>,
    /// Extra env vars (name=value) injected without secrets.
    pub env: Vec<(String, String)>,
}

impl Default for IsolateOptions {
    fn default() -> Self {
        Self {
            name: "mcp".into(),
            image: "scratch".into(),
            read_only_mounts: Vec::new(),
            read_write_mounts: Vec::new(),
            egress_hosts: Vec::new(),
            cpus: "0.5".into(),
            memory: "256m".into(),
            secrets_env_file: None,
            env: Vec::new(),
        }
    }
}

/// Render a Docker Compose v3 fragment for one isolated MCP server.
pub fn render_compose(opts: &IsolateOptions) -> String {
    let service = sanitize_name(&opts.name);
    let mut out = String::new();
    out.push_str("# Generated by `kotro-proxy isolate docker` — review before applying.\n");
    out.push_str("# Kotro does not run this file; it is a profile for Docker MCP Gateway.\n");
    out.push_str("services:\n");
    out.push_str(&format!("  {service}:\n"));
    out.push_str(&format!("    image: {}\n", yaml_string(&opts.image)));
    out.push_str("    read_only: true\n");
    out.push_str("    security_opt:\n");
    out.push_str("      - no-new-privileges:true\n");
    out.push_str("    cap_drop:\n");
    out.push_str("      - ALL\n");
    out.push_str(&format!("    cpus: {}\n", opts.cpus));
    out.push_str(&format!("    mem_limit: {}\n", yaml_string(&opts.memory)));
    out.push_str("    tmpfs:\n");
    out.push_str("      - /tmp:size=64m,mode=1777\n");

    // Volumes.
    let mut volumes: Vec<String> = Vec::new();
    for p in &opts.read_only_mounts {
        volumes.push(format!("{}:/workspace/{}:ro", p.display(), mount_leaf(p)));
    }
    for p in &opts.read_write_mounts {
        volumes.push(format!("{}:/workspace/{}:rw", p.display(), mount_leaf(p)));
    }
    if !volumes.is_empty() {
        out.push_str("    volumes:\n");
        for v in &volumes {
            out.push_str(&format!("      - {}\n", yaml_string(v)));
        }
    }

    // Env + secrets file.
    if !opts.env.is_empty() || opts.secrets_env_file.is_some() {
        out.push_str("    environment:\n");
        for (k, v) in &opts.env {
            out.push_str(&format!("      {}: {}\n", k, yaml_string(v)));
        }
    }
    if let Some(secrets) = &opts.secrets_env_file {
        out.push_str("    env_file:\n");
        out.push_str(&format!("      - {}\n", yaml_string(&secrets.display().to_string())));
    }

    // Network: default deny + explicit egress via a sidecar label.
    out.push_str("    networks:\n");
    out.push_str(&format!("      - {service}-net\n"));
    out.push_str("    labels:\n");
    out.push_str(&format!("      kotro.mcp.server: {}\n", yaml_string(&opts.name)));
    out.push_str(&format!(
        "      kotro.egress.hosts: {}\n",
        yaml_string(&opts.egress_hosts.join(","))
    ));
    out.push_str("\nnetworks:\n");
    out.push_str(&format!("  {service}-net:\n"));
    out.push_str("    driver: bridge\n");
    out.push_str("    internal: ");
    out.push_str(if opts.egress_hosts.is_empty() { "true" } else { "false" });
    out.push('\n');
    out
}

/// Render a short MCP Gateway profile JSON describing the same constraints.
pub fn render_gateway_profile(opts: &IsolateOptions) -> String {
    let profile = serde_json::json!({
        "name": opts.name,
        "image": opts.image,
        "readOnlyRootFilesystem": true,
        "noNewPrivileges": true,
        "capDrop": ["ALL"],
        "resources": {
            "cpus": opts.cpus,
            "memory": opts.memory,
        },
        "mounts": {
            "readOnly": opts.read_only_mounts.iter().map(|p| p.display().to_string()).collect::<Vec<_>>(),
            "readWrite": opts.read_write_mounts.iter().map(|p| p.display().to_string()).collect::<Vec<_>>(),
        },
        "egressHosts": opts.egress_hosts,
        "secretsEnvFile": opts.secrets_env_file.as_ref().map(|p| p.display().to_string()),
        "notes": [
            "Generated by kotro-proxy isolate docker.",
            "Kotro does not execute this profile; apply it via Docker MCP Gateway.",
            "Empty egressHosts → internal (no-egress) network.",
        ],
    });
    serde_json::to_string_pretty(&profile).unwrap_or_else(|_| "{}".into())
}

/// Write both artifacts into `out_dir`. Returns the paths written.
pub fn write_profile(out_dir: &Path, opts: &IsolateOptions) -> Result<(PathBuf, PathBuf), String> {
    std::fs::create_dir_all(out_dir).map_err(|e| format!("create {}: {e}", out_dir.display()))?;
    let compose = out_dir.join(format!("docker-compose.{}.yml", sanitize_name(&opts.name)));
    let profile = out_dir.join(format!("mcp-gateway.{}.json", sanitize_name(&opts.name)));
    std::fs::write(&compose, render_compose(opts))
        .map_err(|e| format!("write {}: {e}", compose.display()))?;
    std::fs::write(&profile, render_gateway_profile(opts))
        .map_err(|e| format!("write {}: {e}", profile.display()))?;
    Ok((compose, profile))
}

fn sanitize_name(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '-' || c == '_' { c } else { '-' })
        .collect::<String>()
        .to_ascii_lowercase()
}

fn mount_leaf(p: &Path) -> String {
    p.file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("mount")
        .to_string()
}

fn yaml_string(s: &str) -> String {
    // Quote when the value has YAML-significant characters.
    if s.is_empty()
        || s.contains([':', '#', '{', '}', '[', ']', ',', '&', '*', '?', '|', '-', '<', '>', '=', '!', '%', '@', '`', '"', '\'', '\\', '\n'])
        || s.starts_with(|c: char| c.is_whitespace())
        || s.ends_with(|c: char| c.is_whitespace())
    {
        format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
    } else {
        s.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn compose_is_read_only_and_internal_by_default() {
        let opts = IsolateOptions {
            name: "files".into(),
            image: "ghcr.io/example/mcp-files:1.0.0".into(),
            read_only_mounts: vec![PathBuf::from("/Users/me/proj")],
            ..Default::default()
        };
        let yaml = render_compose(&opts);
        assert!(yaml.contains("read_only: true"));
        assert!(yaml.contains("no-new-privileges:true"));
        assert!(yaml.contains("cap_drop:"));
        assert!(yaml.contains("internal: true"), "no egress → internal network");
        assert!(yaml.contains("/Users/me/proj:/workspace/proj:ro"));
        assert!(!yaml.contains(":rw"));
    }

    #[test]
    fn egress_hosts_open_the_network() {
        let opts = IsolateOptions {
            name: "web".into(),
            image: "example/web:latest".into(),
            egress_hosts: vec!["api.github.com".into()],
            ..Default::default()
        };
        let yaml = render_compose(&opts);
        assert!(yaml.contains("internal: false"));
        assert!(yaml.contains("api.github.com"));
    }

    #[test]
    fn write_profile_emits_both_artifacts() {
        let dir = tempfile::tempdir().unwrap();
        let opts = IsolateOptions {
            name: "files".into(),
            image: "scratch".into(),
            secrets_env_file: Some(PathBuf::from("/run/secrets/mcp.env")),
            ..Default::default()
        };
        let (compose, profile) = write_profile(dir.path(), &opts).unwrap();
        assert!(compose.is_file());
        assert!(profile.is_file());
        let json: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(profile).unwrap()).unwrap();
        assert_eq!(json["name"], "files");
        assert_eq!(json["readOnlyRootFilesystem"], true);
        assert_eq!(json["secretsEnvFile"], "/run/secrets/mcp.env");
    }
}
