apiVersion: v1
kind: Service
metadata:
  name: {{ include "korto-proxy.fullname" . }}
  labels:
    {{- include "korto-proxy.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-proxy
      protocol: TCP
      name: http-proxy
    - port: {{ .Values.service.metricsPort }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "korto-proxy.selectorLabels" . | nindent 4 }}
